version: "3"

env:
  APP_NAME: strava-cli

tasks:
  build:
    desc: Build
    cmd: go build -o /dev/null

  install:
    desc: Intsall
    cmd: go install

  test:
    desc: Test
    cmd: go test ./...

  coverage:
    desc: Test with coverage
    cmd: go test --cover ./...

  coverage-html:
    desc: Test with coverage in HTML
    cmd: go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html

  open-coverage-html:
    desc: Test with coverage in HTML and open the HTML
    cmds:
      - task coverage-html
      - open coverage.html

  bench:
    desc: Run benchmarks on CPU and memory
    cmd: go test -bench=. -benchmem ./...

  bench-profile:
    desc: Run benchmarks on CPU and memory and create a profile
    cmds:
      - go test -bench=. -benchmem -memprofile ./benchmarks/collection.mem.prof -cpuprofile ./benchmarks/collection.cpu.prof ./collection/

  lint:
    desc: Lint
    cmd: golangci-lint run

  sec:
    desc: Security check
    cmd: gosec ./...

  completion-mac:
    desc: Generate bash completion and save to homebrew
    cmd: $APP_NAME completion bash > /opt/homebrew/etc/bash_completion.d/$APP_NAME

  completion-linux:
    desc: Generate bash completion and save configuration directory
    cmd: $APP_NAME completion bash | sudo tee /etc/bash_completion.d/$APP_NAME

  pull-swagger:
    desc: Pull Jira API swagger definitions (Platform and Software)
    preconditions:
      - sh: command -v curl
        msg: "curl is required but not installed"
    cmds:
      - curl -o swagger.json -sSL https://developers.strava.com/swagger/swagger.json

  generate-swagger:
    desc: Generate Go client from swagger.json using openapi-generator
    preconditions:
      - sh: command -v openapi-generator
        msg: "openapi-generator is required but not installed. Install with: brew install openapi-generator"
      - sh: test -f swagger.json
        msg: "swagger.json not found. Run 'task pull-swagger' first"
    cmds:
      - rm -rf swagger
      - >-
        openapi-generator generate -i swagger.json -g go -o swagger --package-name swagger --additional-properties=isGoSubmodule=true,enumClassPrefix=true --git-user-id alexhokl --git-repo-id strava-cli
      - go mod tidy
