/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the Waypoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Waypoint{}

// Waypoint struct for Waypoint
type Waypoint struct {
	// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
	Latlng []float32 `json:"latlng,omitempty"`
	// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
	TargetLatlng []float32 `json:"target_latlng,omitempty"`
	// Categories that the waypoint belongs to
	Categories []string `json:"categories,omitempty"`
	// A title for the waypoint
	Title *string `json:"title,omitempty"`
	// A description of the waypoint (optional)
	Description *string `json:"description,omitempty"`
	// The number meters along the route that the waypoint is located
	DistanceIntoRoute *float32 `json:"distance_into_route,omitempty"`
}

// NewWaypoint instantiates a new Waypoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWaypoint() *Waypoint {
	this := Waypoint{}
	return &this
}

// NewWaypointWithDefaults instantiates a new Waypoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWaypointWithDefaults() *Waypoint {
	this := Waypoint{}
	return &this
}

// GetLatlng returns the Latlng field value if set, zero value otherwise.
func (o *Waypoint) GetLatlng() []float32 {
	if o == nil || IsNil(o.Latlng) {
		var ret []float32
		return ret
	}
	return o.Latlng
}

// GetLatlngOk returns a tuple with the Latlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Waypoint) GetLatlngOk() ([]float32, bool) {
	if o == nil || IsNil(o.Latlng) {
		return nil, false
	}
	return o.Latlng, true
}

// HasLatlng returns a boolean if a field has been set.
func (o *Waypoint) HasLatlng() bool {
	if o != nil && !IsNil(o.Latlng) {
		return true
	}

	return false
}

// SetLatlng gets a reference to the given []float32 and assigns it to the Latlng field.
func (o *Waypoint) SetLatlng(v []float32) {
	o.Latlng = v
}

// GetTargetLatlng returns the TargetLatlng field value if set, zero value otherwise.
func (o *Waypoint) GetTargetLatlng() []float32 {
	if o == nil || IsNil(o.TargetLatlng) {
		var ret []float32
		return ret
	}
	return o.TargetLatlng
}

// GetTargetLatlngOk returns a tuple with the TargetLatlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Waypoint) GetTargetLatlngOk() ([]float32, bool) {
	if o == nil || IsNil(o.TargetLatlng) {
		return nil, false
	}
	return o.TargetLatlng, true
}

// HasTargetLatlng returns a boolean if a field has been set.
func (o *Waypoint) HasTargetLatlng() bool {
	if o != nil && !IsNil(o.TargetLatlng) {
		return true
	}

	return false
}

// SetTargetLatlng gets a reference to the given []float32 and assigns it to the TargetLatlng field.
func (o *Waypoint) SetTargetLatlng(v []float32) {
	o.TargetLatlng = v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *Waypoint) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Waypoint) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *Waypoint) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *Waypoint) SetCategories(v []string) {
	o.Categories = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Waypoint) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Waypoint) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Waypoint) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Waypoint) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Waypoint) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Waypoint) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Waypoint) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Waypoint) SetDescription(v string) {
	o.Description = &v
}

// GetDistanceIntoRoute returns the DistanceIntoRoute field value if set, zero value otherwise.
func (o *Waypoint) GetDistanceIntoRoute() float32 {
	if o == nil || IsNil(o.DistanceIntoRoute) {
		var ret float32
		return ret
	}
	return *o.DistanceIntoRoute
}

// GetDistanceIntoRouteOk returns a tuple with the DistanceIntoRoute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Waypoint) GetDistanceIntoRouteOk() (*float32, bool) {
	if o == nil || IsNil(o.DistanceIntoRoute) {
		return nil, false
	}
	return o.DistanceIntoRoute, true
}

// HasDistanceIntoRoute returns a boolean if a field has been set.
func (o *Waypoint) HasDistanceIntoRoute() bool {
	if o != nil && !IsNil(o.DistanceIntoRoute) {
		return true
	}

	return false
}

// SetDistanceIntoRoute gets a reference to the given float32 and assigns it to the DistanceIntoRoute field.
func (o *Waypoint) SetDistanceIntoRoute(v float32) {
	o.DistanceIntoRoute = &v
}

func (o Waypoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Waypoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Latlng) {
		toSerialize["latlng"] = o.Latlng
	}
	if !IsNil(o.TargetLatlng) {
		toSerialize["target_latlng"] = o.TargetLatlng
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DistanceIntoRoute) {
		toSerialize["distance_into_route"] = o.DistanceIntoRoute
	}
	return toSerialize, nil
}

type NullableWaypoint struct {
	value *Waypoint
	isSet bool
}

func (v NullableWaypoint) Get() *Waypoint {
	return v.value
}

func (v *NullableWaypoint) Set(val *Waypoint) {
	v.value = val
	v.isSet = true
}

func (v NullableWaypoint) IsSet() bool {
	return v.isSet
}

func (v *NullableWaypoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWaypoint(val *Waypoint) *NullableWaypoint {
	return &NullableWaypoint{value: val, isSet: true}
}

func (v NullableWaypoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWaypoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


